### ISSUE TITLE
Französische Version

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#11]
Französische Version aufbereiten

**Comment by grrd01** [comment]
bitte asap französische Texte liefern.
wohin mit dem Sprach-Selektor: im Header ist schon jetzt wenig Platz. Allenfalls im Hilfe-Modal?

**Comment by bweben** [comment]
![image](https://user-images.githubusercontent.com/10772590/31117734-2d209b6e-a82b-11e7-8a1a-66483925398c.png)
Wie wäre es hier?

**Comment by RouStu** [comment]
Nathanaels Idee gefällt mir: So geht kein Platz auf der Hauptseite verloren, die Sprachauswahl kann aber dennoch direkt im Startbildschirm vorgenommen werden.

Damit ich die Textübersetzung in die Wege leiten kann, müssen die aktuellen Texte auf der online zugänglichen Seite sichtbar sein. Diese sehe ich zurzeit leider noch nicht.

**Comment by RouStu** [comment]
Achtung bei Bildnachweis:
- bei CC-Lizenz: "Mobiliar Lab für Naturrisiken"
- bei geschützter Lizenz: gemäss Übersetzungs-xls

**Comment by RouStu** [comment]
Und: "anonym" -> "anonyme"

**Comment by RouStu** [comment]
Die Version auf dem Server wurde offenbar aktualisiert - besten Dank. Ich habe nochmals einige Anregungen dazu, u.a. aufgrund von Testerrückmeldungen:

Deutsch:
- Hilfemodal/Einstiegssatz: "Diese Bilddatenbank befindet sich..."
- Hilfemodal/Bildkriterien/letzter Punkt: anstelle von "Bilder mit Personen" -> "Bilder von Menschen"
- Hilfemodal/Nutzungsbedingungen/1. Punkt: "...sind Sie dazu berechtigt." -> "sie" sollte klein geschrieben werden
- Hauptfenster/Ortssuche/grauer Text im Feld: anstelle von "Ortschaft wählen" -> "Ortschaft oder Gewässer wählen"

Französisch:
- Der Tabtitel im Browser beinhaltet noch die alte Schreibweise mit "collectif" etc.
- Hilfemodal/Einstiegssatz: "Cette base de données d'images est en..."
- Im Bildnachweis steht nach wie vor "Laboratoire Mobilière"
- Conditions d'utilisation/2. Absatz/2. Punkt: nach "Laboratoire Mobilière de recherche sur les risques naturels" Folgendes einfügen: "de l'Université de Berne"
 - Conditions d'utilisation/2. Absatz/2. Punkt: Abstand einfügen nach dem Punkt zwischen dem 1. und 2. Satz
- Uploadmodal/Titel: anstelle von "Ajoutez ses propres images" -> "Ajouter vos propres images"
- Uploadmodal/unterhalb Titel: anstelle von "Selectionner..." -> "Sélectionner"
- Hauptfenster/Ortssuche/grauer Text im Feld: anstelle von "sélectionner une localité" -> "sélectionner une localité ou un cours d'eau"

Bei Unklarheiten bitte melden.

**Comment by grrd01** [comment]
@RouStu : habe deine Ergänzungen eingepflegt. Einzig diesen Punkt verstehe ich nicht:
- Im Bildnachweis steht nach wie vor "Laboratoire Mobilière"
Was soll denn dort stattdessen stehen? Wo steht der gewünschte Text?

**Comment by RouStu** [comment]
Danke!
Gemäss Kommentar weiter oben und Besprechung (glaube diese oder letzte Woche): "Mobiliar Lab für Naturrisiken" - auch in der französichen Version. Deutsch auf der französichen Seite ist zwar etwas unschön, allerdings sehe ich folgende Gründe, die dafür sprechen:
- "Laboratoire Mobilière" ist nicht eindeutig, da es noch weitere Labs gibt.
- "Laboratoire Mobilière de recherche sur les risques naturels" ist zu lang.
- Mit der deutschen Version des Namens sind wir in Übereinstimmung mit dem Namen im Logo.

**Comment by grrd01** [comment]
ok, war mir nicht klar, dass obige Angabe für beide Sprachen gilt.
erledigt

**Comment by RouStu** [comment]
Nochmals kurz ein paar wenige Texttorrekturen:

Französisch:
- Hilfemodal/Ortssuche: "Sélectionner les images" statt "Sélectionner des images"
- Conditions d'utilisation/2. Punkt: "naturelsde" mit Abstand

Deutsch:
- Hilfemodal/Suche nach Zeit: "Bilder" statt "Fotos"
- Hilfemodal/Bildkriterien/letzter Punkt: anstelle von "Bilder mit Personen, die im Fokus..." -> "Bilder von Menschen, die im Fokus..."

**Comment by grrd01** [comment]
fixed

**Comment by RouStu** [comment]
Alle Kommentare von oben passen.
Noch etwas Neues:
Conditions de licence/geschützte Lizenz: Nach dem zweiten Satz bitte Abstand einfügen ("concernée).Les images")

**Comment by grrd01** [comment]
fixed
