### ISSUE TITLE
Mail an User wenn sein Bild validiert

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#12]

**Comment by RouStu** [comment]
Funktioniert bei mir noch nicht, wenn ich die Checkbox im Adminmodus aktiviere und "Verwerfen" oder "Speichern und aktivieren" klicke.

**Comment by bweben** [comment]
Funktioniert nur wenn eine email Adresse im Bild ist, war dies der Fall?

**Comment by grrd01** [comment]
Bei Rouven gehen mailto-Links im Chrome generell nicht mehr. Kein Fehler unserer App.

**Comment by RouStu** [comment]
Yes, nun wird tatsächlich ein Mail im Outlook geöffnet!

Ein weiteres Problem ist aber aufgetaucht: Der Link zu den Bildkriterien im Mail bei Ablehnung lautet http://138.68.87.41/de/admin/#collapse2
Und bei Annahme: http://138.68.87.41/de/admin/5a0d49a5a2e8a955d36f34da

**Comment by bweben** [comment]
Das ist nun auch geflickt.

**Comment by RouStu** [comment]
Noch zwei Fragen hierzu:
- Der Link bei Ablehnung führt mich auf den Startbildschirm "Willkommen". Könnte dort gleich das Tab "Bildkriterien" geöffnet werden?
- Könnte es eingerichtet werden, dass wenn das Bild in der frz.-Version heraufgeladen wird, die Nachricht auf frz. verschickt wird? Bei meinen Tests gab's immer die deutsche Nachricht...

**Comment by bweben** [comment]
- Müsste eigentlich möglich sein.
- Das ist so gewollt, die Sprache wird entsprechend dem, der das Bild hochgeladen hat angepasst und nicht entsprechend dem, der es validiert.

**Comment by RouStu** [comment]
OK. Ist die Sprache der Validierungsnachricht denn von der Browsersprache oder vom Bilddatenbank-Sprachmodus abhängig?
Bei meinem Test gestern hatte ich das Bild eben im französischen Bilddatenbank-Sprachmodus hochgeladen und es wurde eine deutsche Nachricht generiert.

**Comment by bweben** [comment]
Stimmt merci fürs finden, ist nun geflickt.

**Comment by RouStu** [comment]
Die Sprache des Bilddatenbank-Sprachemodus wird nach meinen Tests noch nicht korrekt übernommen. Im Adminmodus steht bei der Benutzersprache deutsch, obwohl ich das Bild im franz. Modus hochgeladen habe. Entsprechend wird bei mir kein franz. Mail als Vorlage erstellt bei der Validierung.

**Comment by bweben** [comment]
Hast du anschliessend auf dem gleichen Gerät wie du das Bild hochgeladen hast die Sprache wieder auf deutsch geändert? Falls dies der Fall ist, ist das "Problem", dass die Sprache des Benutzers nicht im Bild direkt gespeichert ist sondern referenziert wird.
Das heisst, wenn der Benutzer nach dem hochladen des Bildes die Sprache wieder wechselt ist auch "die Sprache" des Bildes gewechselt.

**Comment by RouStu** [comment]
Das scheint das "Problem" tatsächlich zu erklären =). Wird also immer die zuletzt bekannte Sprache des Users dem Bild zugeordnet? Wie lange funktioniert diese Referenzierung (bis er den Cache löscht oder die IP-Adresse ändert...)?

In der franz. Version des Mails fehlt nun noch der Link zu den Bildkriterien bei Ablehnung.

**Comment by bweben** [comment]
Die Sprache bleibt "konsistent" solange der der Benutzer auf seinem Browser bleibt und auf dem gleichen Gerät. Ausserdem darf er die gespeicherten Daten der Applikation nicht löschen (ist nicht gelöscht bei einem Cache leeren). Wenn dies anders sein soll, müsste sich der Benutzer anmelden was umständlich und in der restlichen Zeit nicht mehr zu implementieren wäre.

**Comment by RouStu** [comment]
OK, danke. Nur um die Sache richtig zu verstehen, nochmals eine kurze Rückrage: Wenn der Benutzer die gespeicherten Daten der Applikation löscht, bleibt dann die zu diesem Zeitpunkt eingestellte Sprache definitiv in der Datenbank vorhanden, ohne dass sie sich jemals wieder ändern würde?

**Comment by bweben** [comment]
Ja

**Comment by RouStu** [comment]
In der franz. Ablehnungsmail fehlt bei mir immer noch der Link zu den Bildkriterien.

**Comment by bweben** [comment]
ist geflickt
