### ISSUE TITLE
Autokennzeichen unkenntlich machen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#13]
- diskutierte Möglichkeit: Bereich mit Nummer auf schlechte Auflösung rechnen (verpixeln) und wieder ins Bild einfügen
- Erkennungsvarianten: manuell vs. automatisch

**Comment by grrd01** [comment]
dürfte recht aufwändig werden. wer etwas anonymisieren will, macht das ev besser direkt in Photoshop. Als Wunsch auf Prio 3 zurückstellen?

**Comment by RouStu** [comment]
Wird wegen grossem Aufwand zurückgestellt.
