### ISSUE TITLE
Kartenhintergrund um CH hell

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#14]
Karte mit hellem Hintergrund anstatt dunklem, mit leicht dickerer Grenzlinie, damit sich die Schweiz besser vom Ausland abhebt

**Comment by grrd01** [comment]
Farbe und Breite der Grenzlinien lassen sich nicht beeinflussen, diese werden vom Imageprovider generiert.
Die umligenden Länder lassen sich zwar weiss aufhellen (anstatt sie grau abzudunkeln), das sieht aber hässlich aus:

![image](https://user-images.githubusercontent.com/5230177/30276140-2459c4ac-9704-11e7-851d-9b5ddc8ef5c0.png)


@RouStu : wollt ihr das wirklich?

**Comment by RouStu** [comment]
Danke für die Erläuterungen, Gérard.
Die Mehrheit meiner Teammitglieder war der Meinung, dass der weisse Hintergrund in diesem Zusammenhang passender ist. Allerdings würde die Karte wohl noch schöner (oder wenigstens weniger wüst, in Deinen Augen), wenn die Transparenz der weissen Farbe noch etwas erhöht würde. Falls die adaptierte Karte von vielen Leuten in der kommenden Zeit auch als unschön empfunden wird, denke ich, dass eine entsprechende Änderung schnell vorgenommen wäre...

**Comment by grrd01** [comment]
Jetzt ist es weiss.
brrr..
