### ISSUE TITLE
Georeferenzierungsmodus

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#15]
Georeferenzierungsmodus: Angabe von Name und E-Mail (E-Mail freiwillig und nicht sichtbar auf Webseite -> interessant, um Leute, die viele Fotos georeferenzieren, zu ermitteln oder für allfälligen Wettbewerb)

**Comment by grrd01** [comment]
Zusätzliche Überlegung: aktuell lässt der Georeferenz.modus vandalismus zu: ein korrekt referenziertes Bild kann nach irgendwo verschoben werden, die ursprünglichen, korrekten Daten sind verloren. Müssen wir das absichern? 2 Koordinaten-angaben: original und georef, danach Validierung in Admin-Konsole?

**Comment by RouStu** [comment]
Ich fände dieses Vorgehen sehr sinnvoll.

**Comment by RouStu** [comment]
Gemäss Absprache: Koordinatenangaben werden bei Intialverortung doppelt gespeichert; im Verortungsmodus wird das Doppel der Koordinaten überschrieben; diese Koordinaten sind ausschlaggebend für die Anzeige des Bildstandortes.

Idee dahinter: Bei einer missbräuchlichen Zweitverotung könnte eine Funktion eingebaut werden, um die Initialverortung zu rekonstruieren.

**Comment by bweben** [comment]
Die Koordinaten / der Ort werden nun noch zusätzlich gespeichert.

**Comment by RouStu** [comment]
Funktioniert bestens.
Einzig etwas, das ich schon einmal im Adminmodus entdeckt hatte, ist mir auch im Georef.-Modus aufgefallen (mein entsprechender Screenshot ist leider nicht mehr in der Zwischenablage): Es handelte sich um einen Pin, der über einem Cluster mit der Zahl "2" angezeigt wurde. Beim Klicken auf den Cluster sind drei Pins erschienen. Nach dem Verschieben des Pins war nur noch ein Pin am neuen Standort sichtbar.

**Comment by bweben** [comment]
Wie kommen die Pins zum Vorschein? Sind sie anschliessend wirklich als 3 Pins an unterschiedlichem Ort vorhanden oder sieht die Animation aus als würde ein Pin aus dem Cluster "kommen"?

**Comment by RouStu** [comment]
Die 3 Pins wurden alle am selben Ort angezeigt.
Hier ein ähnliches Problem in Bellinzona (Georef.-Modus über Pin des Bildes aufgerufen): Da sollte nur ein Pin sein. Und Bildvorschau bei Pin-Hover nicht möglich.
![image](https://user-images.githubusercontent.com/31846871/33209873-32a4f02e-d118-11e7-9d5d-d791023de0a7.png)

**Comment by RouStu** [comment]
![image](https://user-images.githubusercontent.com/31846871/33209969-94f8ef0a-d118-11e7-9a32-5a0974fd4f6c.png)

**Comment by bweben** [comment]
Merci fürs Finden, ist nun geflickt.

**Comment by RouStu** [comment]
Super! Ich gehe davon aus, dass - falls das Problem auch im Adminmodus autritt - dort ebenfalls behoben wurde.

**Comment by bweben** [comment]
Genau :)

**Comment by RouStu** [comment]
Zwei Dinge zum Gereferenziermodus soeben aufgefallen (sorry, wenn dies bereits behoben ist, aber noch nicht auf dem Server):
- das Feld "darf publiziert werden" ist sichtbar und lässt sich verändern (obwohl die Veränderung offensichtlich keinen Einfluss auf die Metadaten hat); dieses Feld sollte in diesem Modus entweder weg sein oder zumindest nicht modifizierbar
- habe soeben im Georefmodus das Bild 5a0aa6eb4847a129cefe5777 in den Lago Maggiore gezogen; im Adminmodus sind zu diesem Bild nun weder die gesicherten Koordinaten noch der "Rücksetz"-Knopf vorhanden; woran könnte es liegen?

**Comment by RouStu** [comment]
A propos "darf publiziert werden": Die Deaktivierung dieser Checkbox im Adminmodus hat zurzeit noch keine Wirkung aufs Bild im Normalmodus.

**Comment by bweben** [comment]
- Das Feld "darf publiziert werden" ist nicht mehr aktiv (lässt sich nicht mehr verändern) hat deshalb auch keine Änderung aufs Bild, kann nur der, der es hochlädt ändern.
- Die Änderung mit den Original Koordinaten ist erst bei neuen Bildern aktiv, da diese (die Original Koordinaten) beim erstmaligen Upload gesetzt werden.
