### ISSUE TITLE
Detailansicht: Texte

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#20]
Zusätzlich zu bestehenden Elementen:
- exakter Lizenzname erscheint unter „Lizenz“
- ein „?“ führt zum Lizenzbeschrieb im Hilfebereich
- Koordinaten erscheinen bei Ort
- Bildnachweis erscheint darunter (evtl. kleinere Schrift)

**Comment by RouStu** [comment]
Verlinkungen ermöglichen (z.B. auf gra-nat.ch). Sinnvoll wahrscheinlich im Beschreibungs-Feld.

**Comment by grrd01** [comment]
Im Bildnachweis oder daneben einen direkten Link auf die Detail-Ansicht des aktuellen Bildes

**Comment by grrd01** [comment]
aktuell siehts so aus:
der Detail-Schirm enthält Lizenzbezeichnung, Bildnachweis und den direkten Link auf dieses Bild in der Applikation.
die letzteren beiden können per Knopfdruck ins Clipboard kopiert werden.
die Beschreibung kann links auf webseiten und mail-adressen enthalten, welche anklickbar sind.
