### ISSUE TITLE
Zeit-Slider: Skalierung ist benutzerfreundlich

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#22]
Ereignisdaten von alten bis zu aktuellen Fotos werden benutzerfreundlich dargestellt

**Comment by grrd01** [comment]
Absprache mit Luzius: Problematik wird zurückgestellt, bis sie wirklich auftritt. Lösungsansätze sind vorhanden.

**Comment by RouStu** [comment]
Vorschlag einer logarithmischen Formel gemäss separater Mail.
Einbau wird ausprobiert, sobald genügend Zeit dafür vorhanden ist.

**Comment by bweben** [comment]
Ist nun mit x^20 implementiert.
