### ISSUE TITLE
Zeit-Slider: Tooltipps werden praktisch angezeigt

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#23]
Das ausgewählte Zeitfenster wird so angezeigt, dass eine optimale Bedienung möglich ist.
Diskutierte Möglichkeit: Monat und Jahr anzeigen (ohne Tag).

**Comment by grrd01** [comment]
"praktisch" ist ein dehnbarer Begriff.
Anzeige im Format jjjj-mm (ISO 8601:2004), jjjj.mm, mm.jjjj, ... sind möglich.
@RouStu : Soll ich hier schon was ändern? Oder ist dieser Issue mehr so eine Diskussionsgrundlage? Welches Format wird gewünscht?

**Comment by RouStu** [comment]
Mir scheint zurzeit das Format mm.jjjj am "praktischsten". Kannst Du sehr gerne so anpassen.

**Comment by grrd01** [comment]
fixed
