### ISSUE TITLE
Bildeigenschaften (gewisse Elemente näher zu bestimmen)

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#24]
Diskussion:
- Speicherung der Originalbilder in voller Qualität; zu definieren, ob Ablage in DB oder Ordner
- akzeptierte Formate: JPG, PNG, BMP, GIF, TIFF, weitere?
- geschützte Bilder: Bildanzeige mit 1000 Pixel für längste Seite des Bildes, ohne Downloadknopf
- Creative Commons: Bildgrösse für Bildanzeige zu definieren, Download (bzw. Anzeige in neuem Tab) in voller Qualität

**Comment by bweben** [comment]
Wie sieht es mit den Thumbnails aus?
300 * 200 wäre auf FullHD Displays ungefähr das Grösste, was angezeigt wird.
Auf 4K Displays könnte diese Grösse aber auch 600 * 400 sein.

**Comment by bweben** [comment]
Bilder werden (falls geschützt, noch nicht implementiert) auf max Höhe oder wenn Breite grösser ist auf max Breite 1000px gesetzt.
Auf dem Server müssen thumbnails auf 300px*200px gerechnet werden.

**Comment by bweben** [comment]
Thumbnails werden nun auch berechnet und verwendet.

**Comment by RouStu** [comment]
Sieht sehr gut aus.
@bweben: Könntest Du mir bitte eine Mini-Tabelle anfertigen (ohne ausgeklügelte Formatierung, rein informativ), aus der man einen Überblick über die Eigenschaften der Bilder je nach Lizenz gewinnt: Akzeptierte Maximalgrösse (plus was geschieht bei Überschreitung), Grösse Bildspeicherung in DB, Grösse Bildanzeigen (Thumbnails, Detailansicht, Download) plus Weiteres (z.B. Vorgehen bei zu kleinen Bildern, akzeptierte Formate...)? Merci!
