### ISSUE TITLE
Bilder Hochladen: Eingegebene Werte behalten

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#26]
Die eingegebenen Werte bleiben bestehen, wenn das Modal geschlossen wird.
Email, Name, Lizens ... sollen auch beim nächsten Bild schon wieder ausgefüllt sein.
Bild, Koordinaten, Ortschaft, Beschreibung sollen erst beim Senden geleert werden

**Comment by bweben** [comment]
Wird nun gecached.

**Comment by grrd01** [comment]
ja, wenn das modal geschlossen wird, sind nun alle Werte (ausser AVB akzeptieren) noch vorhanden.
wenn nach "senden" aber ein weiteres Bild hochgeladen wird, sind alle Felder leer. Email, Name, Lizenz ... sollten auch fürs nächste Bild erhalten bleiben.

**Comment by RouStu** [comment]
Funktioniert fast:
- Wenn ich die geschützte Lizenz auswähle und das Bild sende, ist beim nächsten Öffnen des Uploadmoadals wieder die CC-Lizenz standardmässig drin.
- Bei mir im Chrome kann ich im Beschreibungsfeld immer noch an mehreren Stellen ins Feld klicken; der Cursor blinkt dann dort und nicht am Anfang des Feldes.

**Comment by bweben** [comment]
Punkt 1 funktioniert nun.
Punkt 2 konnte ich leider nicht nachproduzieren... 
> Hat dein Bild Metadaten? Welche Google Chrome Version verwendest du?

**Comment by RouStu** [comment]
Danke.
Punkt 2:
- Version 59.0.3071.104 (Offizieller Build) (64-Bit)
- Wenn ich den Cache leere, die Webseite öffne, das Willkommensmodal schliesse und das Uploadmodal öffne, ist das Beschreibungsfeld leer (s. erstes Bild unten; d.h. ohne Text "Beschreibung des Bildes"; im Gegensatz z.B. zu "Urheber", wo im Feld "Vorname Name" steht, bevor man ins Feld klickt). Wenn ich dann ins Feld klicke, kann ich in einem Teil des Feldes Leerschläge markieren (s. Bild 2 unten). Sobald ich diese lösche, erscheint der graue Text "Beschreibung des Bildes". Ich hoffe, das ist einigermassen verständlich.

![image](https://user-images.githubusercontent.com/31846871/32059706-3ebc40a4-ba6d-11e7-92ac-3ffe095e311c.png)

![image](https://user-images.githubusercontent.com/31846871/32059935-c7cc807a-ba6d-11e7-9f85-833aa6e11160.png)

**Comment by RouStu** [comment]
Hab noch ein wenig weiter probiert: Das Problem scheint tatsächlich mit den Metadaten zusammenzuhängen. Je nach Bild kommen die Leerzeichen wie oben beschrieben, oder das Beschreibungsfeld wird bereits ausgefüllt mit Text.

Es kann allerdings auch folgender Fall vorkommen: man wählt ein Bild aus, das das Beschreibungsfeld mit Text ausfüllt. Dann wählt man ein anderes Bild aus (ohne das Bild zu senden) und der Beschreibungstext des vorherigen Bildes bleibt erhalten.

Falls diese Problembeschreibung schriftlich zu kompliziert ist, können wir gerne mal zusammensitzen.
Unten hänge ich noch das Bild an, das mir die Leerzeichen ins Beschreibungsfeld schreibt.
![file131](https://user-images.githubusercontent.com/31846871/32060850-494d70f8-ba70-11e7-80cf-6e28ba72df07.jpg)

**Comment by bweben** [comment]
Hallo Rouven,
das ist so verständlich.
Es werden nun alle Leerschläge vor und hinter dem Text abgeschnitten d.h:
`         hallo   ` > `hallo`
`                    ` > ``
`          hallo welt    ` > `hallo welt`

Ich hoffe dies ist so i.O.

**Comment by RouStu** [comment]
=)
Sehr gut, besten Dank!

**Comment by grrd01** [comment]
Mein Teil des Problems ist behoben.
@RouStu : Falls deine Punkte auch ok sind, kannst du den Defect schiessen.

**Comment by RouStu** [comment]
Meine Punkte sind soweit auch behoben. Ich wollte noch eine Frage in diesem Zusammenhang mit Euch besprechen. Das Urheberfeld ist ja kein Muss-Feld:
- falls es leer ist, sollte als Urheber "anonym" stehen (haben wir im Juli mal so besprochen; können diesen Punkt aber nochmals zusammen anschauen, da ein Bild so ziemlich schnell "anonym" wird),
- falls das Autorenfeld in den EXIF-Daten leer ist, fände ich es persönlich von Vorteil, wenn statt dem Rechteck nichts automatisch ins Feld geschrieben würde.

**Comment by grrd01** [comment]
@RouStu : Ist hier noch etwas offen oder kann das weg?
