### ISSUE TITLE
Datumsfeld in Uploadmodal kann keine reinen Jahrzahlen annehmen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#3]
- Variante: Text- statt Datumsfeld
- erwünscht: Zeit aus Exif kann gespeichert werden

**Comment by RouStu** [comment]
Falls, wie besprochen, als Format das Datumsformat gewählt wird, Hilfetext darüber entsprechend anpassen.

**Comment by grrd01** [comment]
Allenfalls Datum bei unbekanntem Tag auf Monatsanfang, bei unbekanntem Monat auf Jahresanfang setzen lassen. So kann der einfache & sichere Datepicker verwendet werden, der Jahr alleine nicht unterstützt.
