### ISSUE TITLE
Schweizergrenze aus Swissboundaries

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#30]
Da zurzeit zwei verschiedene Grenzen existieren, die sich z.T. überschneiden, soll die Grenze aus Swissboundaries darübergelegt werden. Diese Grenze sollte breiter sein als die beiden zurzeit sichtbaren. Farbe entweder schwarz oder grün.

**Comment by grrd01** [comment]
@RouStu : in my humble opinion entfernen wir uns aktuell immer weiter von einer modernen, schlanken und einheitlichen Design. Noch vor wenigen Wochen hast du mich auf den blauen Slider angesprochen, welcher farblich nicht zum Rest passe. Unterdessen hinterlegen wir Listenpunkte hellgrün und rosarot, übermalen Diskrepanzen zwischen einem scharzen und einem weissen Layer mit fetten grünen Linien. Es fehlen nur noch Katzenbilder und wir sind beim Worst-Case-Szenario hochwasserrisiko.ch

Es gibt Elemente, die wir beeinflussen können, und es gibt Elemente die wir nicht beeinflussen können. Das Kartenlayout von Leaflet/Mapbox können wir nicht anpassen, das von Google Maps könnten wir auch nicht. Wir können Grenzverläufe und Ortschaftsnamen weder farblich noch örtlich verändern. Wir wissen nicht, welche Datensätze dafür als Grundlage dienen.

Wir können aber versuchen, das beste aus den gegebenen Möglichkeiten zu machen, und die Elemente, die wir beeinflussen können, so zu gestalten, dass sie möglichst harmonisch zu den gegebenen passen.

Wenn wir einen Weissen Layer um die Schweiz legen, welcher nie ganz den Leaflet-Grenzen entsprechen kann, erhalten wir diesen Zustand:
![image](https://user-images.githubusercontent.com/5230177/30683264-03286116-9ead-11e7-9ee0-893837838859.png)
Grenze und Ortsnamen werden grau, wo sie vom weissen Layer überlagert werden. Wir können die weisse Ebene nicht hinter den Text legen, dieser ist fixer Bestandteil der Karte.

Wenn wir nun versuchen, diese Diskrepanz mit einer fetten grünen Linie zu kaschieren, siehts danach so aus: 
![image](https://user-images.githubusercontent.com/5230177/30683449-cc9d6f82-9ead-11e7-929c-7a140d310776.png)

Wenn wir statt einer weissen dagegen eine schwarze Abdeckung verwenden, können wir einige Probleme mindern, da schwarzer Text immer noch schwarz ist, wenn man ihn schwarz überlagert:
![image](https://user-images.githubusercontent.com/5230177/30683805-27acb40e-9eaf-11e7-93a2-2a9397d3d5d4.png) 
Das Problem, dass sich die Grenzverläufe nicht decken, bleibt freilich bestehen. 
Aber wenigstens wird die Grenze so nicht grau-schwarz gestreift

Die einzige echte Alternative in meinen Augen wäre es, auf die Umrandung der Schweiz komplett zu verzichten. Dabei geht aber die Hervorhebung der Schweiz verloren, was in für mein Empfinden für eine Webseite, die die Schweiz ins Zentrum stellen will, den grösseren Verlust darstellt als die minimen Unsauberheiten am Grenzverlauf.

Losgelöst von dieser Diskussion habe ich im moment ein schlechtes Gefühl, was unsere Zusammenarbeit betreffend der Weiterentwicklung und Fertigstellung des aktuellen Poduktes angeht. Wir verlieren uns in grafischen Details und schwammig formulierten Anliegen und verlieren die wesentlichen Punkte aus den Augen. Wir riskieren, einen Zustand zu erreichen, wo dieses Ding nie mehr fertig wird.

Selbstverständlich seid ihr der Auftraggeber und ihr dürft euch wünschen, wie das Ergebnis aussehen soll. Mir dagegen fällt es schwer, mein Herzblut in etwas zu stecken, hinter dem ich nicht stehen kann. Es wäre schade, wenn dies zu einer reinen Auftragsabwicklung verkommt.

Müssten wir allenfalls mal eine Stunde mit einem Grafiker zusammensitzen, damit wir zumindest in den optischen Fragen den Input eines Profis hätten?

**Comment by grrd01** [comment]
In Absprache mit Luzius wird das Ausland nun mit einem helleren Grau abgedeckt. Die grüne Linie entfällt.
