### ISSUE TITLE
Hilfetext: Bildkriterien

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#31]
Die Bildkriterien wie in der Vorlage einander gegenüberstellen, da die jeweiligen Zeilen Gegensätze aufzeigen (was wir wollen und was nicht).

**Comment by grrd01** [comment]
Dies ist vielleicht keine besonders gute Idee. Einerseits bleibt viel Platz ungenutzt, andererseits ist spätestens auf dem Smartphone sowieso kein Platz für ein 2-Spalten-Layout.

**Comment by RouStu** [comment]
Die Bildkriterien in der jetzigen Form sind jedenfalls weniger logisch und verständlich als wenn sie "gepaart" erscheinen.

Für die Desktop-Version habe ich platzmässig keine Bedenken. Für die mobile Anwendung sehe ich Deinen Einwand allerdings sehr wohl. Wie sähe es denn aus, wenn wir eine Methode von hier adaptierten: 
https://blog.kulturbanause.de/2012/06/tabellen-im-responsive-webdesign/
Z.B. horizontal scrollbare oder zoombare Tabelle?

**Comment by grrd01** [comment]
@RouStu : Horizontal scrollbar halte ich für einen Designfehler. Eine App sollte nicht in 2 Richtungen gleichzeitig scrollbar sein, die meisten Apps und mobilen Betriebssysteme scrollen auf kleinen Bildschirmen nach unten. Dieser Ansatz entspricht auch dem hier eingesetzten Framework Bootstrap, welches defaultmässig Zeilen umbricht, wenn sie zu  lang werden.
Zoombar macht auch nicht glücklicher, das raus- und reinzoomen ist ein Gefummel, zudem dürfte die Totalansicht nicht lesbar sein.
Ein Beispiel, wie Tabellen mobil dargestellt werden können, findest du bereits in unserer App unter Verwendete Software von Dritten. Auch dieser Ansatz hilft hier aber nicht wirklich weiter. Die einzigen sinnvollen Lösungen scheinen mir:

- ja
- ja
- ja
- nein
- nein
- nein

oder: 

- ja
- nein
- ja
- nein
- ja
- nein

**Comment by RouStu** [comment]
Letzterer Vorschlag könnte fruchten - eventuell mit dezenter farblicher Unterstützung oder Gutzeichen/Kreuz anstelle von Bullet Points.

**Comment by grrd01** [comment]
farbliche Hervorhebung habe ich befürchtet.. siehe auch http://theoatmeal.com/comics/design_hell ;-)

**Comment by grrd01** [comment]
Wie soll in diesem Fall die Überschrift aussehen?

Beinhaltet/beinhaltet nicht…

**Comment by RouStu** [comment]
Passt.
