### ISSUE TITLE
Lizenztext geschützte Bilder

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#32]
Für die geschützten Bilder den Lizenztext gemäss dem effektiven Vorgehen ergänzen:
- "Die Bilder werden verkleinert, um Missbrauch zu vermeiden." oder
- "Die Bilder werden auf 1000 Pixel Breite bzw. Höhe verkleinert."

Falls Ihr eine andere Textvariante bevorzugt, nur zu. Mir scheint die grundsätzliche Aussage, dass sich die Bildauflösung der beiden Lizenzen unterscheidet, jedenfalls eine wichtige.

**Comment by grrd01** [comment]
fixed. der komplette text lautet nun:
©, alle Rechte vorbehalten: Die Bilder sind ausschliesslich zur Ansicht bestimmt. Für die Weiterverwendung der Bilder ist in jedem Fall die Zustimmung des Rechteinhabers (siehe jeweilige E-Mail-Adressen) einzuholen. Die Bilder werden auf 1000 Pixel Breite bzw. Höhe verkleinert, um Missbrauch zu vermeiden.
