### ISSUE TITLE
Download privater Bilder

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#33]
bei grünen 'for your eyes only' Pins aus der DB funktioniert der download-button im Detail Modal nicht (bilder mit CC-Lizenz  haben dort einen Download-Button im Modal-Header

**Comment by bweben** [comment]
Wie meinnst du "funktioniert nicht"? Der Button macht bei allen Bildern bei mir dasselbe.

**Comment by grrd01** [comment]
grüne Pins, welche bereits in der DB, aber noch nicht validiert sind, haben (sofern mit CC-Lizenz) auch einen Download Button. 
ist: Wenn ich auf diesen klicke, passiert nichts.
soll: Wenn ich auf diesen klicke, öffnet sich wie bei den anderen das Bild in einem neuen Tab.

**Comment by bweben** [comment]
Das funktioniert bei mir...

**Comment by grrd01** [comment]
neu hat Chrome hier grundlegende Securitybedenken: 
Not allowed to navigate top frame to data URL:
https://stackoverflow.com/questions/45493234/jspdf-not-allowed-to-navigate-top-frame-to-data-url

**Comment by grrd01** [comment]
fixed. neu wird eine funktion aufgerufen, die ein neues html-dokument erzeugt und öffnet: 
`const wnd = window.open('about:blank', '');
    wnd.document.write('<img src="' + this.detail.image + '">');
    wnd.document.close();`

**Comment by bweben** [comment]
Top merci 👍

**Comment by grrd01** [comment]
geht.
