### ISSUE TITLE
Kartendarstellung kaputt in Modal Submit

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#34]
Vorgehen: 
- Modal Submit öffnen, Bild wählen, Pin in Karte setzen, allenfalls Angaben einfüllen.
- Modal schliessen
- Modal wieder öffnen
Ergebnis:
- Die eingegebenen Werte sind zwar wieder da, die Karte ist aber grossmehrheitlich leer.

**Comment by bweben** [comment]
fixed

**Comment by grrd01** [comment]
sensationell!
