### ISSUE TITLE
Klick auf die Karte funktioniert nicht mehr

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#35]
Beim klicken auf die Karte passiert nichts mehr.
Soll: Grauer Pin setzen, umliegende Photos anzeigen

**Comment by grrd01** [comment]
Hier ist beim Service etwas kapput gegangen. es wird zwar noch etwas aufgerufen, es gibt aber nie daten zurück

**Comment by grrd01** [comment]
Offensichtlich funktioniert die zusammenlegung der webservices bootstrap-map, welche mit lat/long oder string aufgerufen werden können, nicht korrekt.

**Comment by bweben** [comment]
Funktioniert wieder.

**Comment by grrd01** [comment]
indeed 🥇
