### ISSUE TITLE
Neue Bilder nicht sichtbar

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#36]
Wurde ein neues Bild hochgeladen, ist dieses zunächst nicht sichtbar, weder als grüner Pin auf der Karte, noch als Preview in der Liste. Erst nach einem Reload kommt dieses zum Vorschein.

Soll: das neue bild wird sofort sichtbar, grün auf der Karte und in der Bildliste

**Comment by bweben** [comment]
Konnte nicht nachvollzogen werden.
