### ISSUE TITLE
Übernahme von Daten und Koordinaten aus Exif defekt

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#38]
Wird im Upload-Modal ein Bild ausgewählt, wird das Datum und die Koordinaten nicht mehr übernommen.
Bitte bei einem Refactoring sicherstellen, dass die grundlegenden Mechanismen noch funktionieren, bevor ein Commit durchgeführt wird.

**Comment by bweben** [comment]
Ist nun wieder geflickt.

**Comment by grrd01** [comment]
yep!
