### ISSUE TITLE
Kopieren von Bildnachweis beinhaltet HTML-Lizenzlink

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#41]
Zur Diskussion: Ist es möglich, das Kopieren so einzurichten, dass beim Kopieren des Bildnachweises der Link "<a href..." nicht mitkopiert wird? Oder ist dies eben gerade wichtig?
Die Frage ist, ob diese Funktion eher dazu genutzt wird, den Bildnachweis ins Word zu kopieren oder auf eine andere Webseite.

**Comment by grrd01** [comment]
@RouStu : Müsste beides möglich sein. Wünsch dir was ;-)

**Comment by RouStu** [comment]
OK =). Ohne Link bitte.

**Comment by grrd01** [comment]
fixed.
