### ISSUE TITLE
Upload: Lizenz "zur Wiederverwendung" als default

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#42]

**Comment by grrd01** [comment]
fixed. Zudem wird das Modal Upload nicht mehr verkleinert, wenn nach der Wahl eines Bildes ein zweites mal der Explorer zur Auswahl eines Bildes geöffnet wird, und dieser dann mit abbrechen oder schliessen weggeklickt wird.

**Comment by grrd01** [comment]
Bei multi-Upload bleibt nun auch die Auswahl "bin mit den AVBs einverstenden" erhalten.
