### ISSUE TITLE
Detailansicht: Koordinatenanzeige

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#45]
- Zurzeit werden in der Detailansicht die Koordinaten mit zwischen 14 und 17 Kommastellen angegeben (jedenfalls geht dies aus drei Fotos hervor).
- Die Änderung der 5. Kommastelle der dezimalen WGS84-Koordinaten um +/-1 entspricht ca. einem Meter. 
- Auf Google Maps werden bei einem Klick in die Karte 6 Kommastellen angezeigt.

Mein Vorschlag ist, die Anzeige nach der 5. Kommastelle abzuschneiden bzw. nicht mehr anzuzeigen.

Nicht prioritär, da Detail.

**Comment by grrd01** [comment]
fixed
