### ISSUE TITLE
Admin-Modus: statistische Werte

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#46]
Vorschlag für einige statistische Werte betreffend die hochgeladenen, validierten Bildern mit dem Zweck, einen Überblick über den jeweils aktuellen Inhalt der Datenbank zu gewinnen:

- Anzahl neue Bilder in einem bestimmten Uploadzeitraum (pro Lizenztyp)
- Anzahl Bilder pro Urheber: max., min., Mittelwert
- evtl. Rangliste mit Urhebern bez. Anzahl Bildern 

Falls Ihr im gleichen Atemzug weitere aufschlussreiche Angaben erschliessen könnt, nur zu.

**Comment by RouStu** [comment]
Was ich eben noch sagen wollte (falls Aufwand überschaubar): Anzahl Einträge in Rangliste gerne flexibel gestalten und nicht auf drei limitiert. Merci.

**Comment by RouStu** [comment]
Um in der Statistik die Bilder, die heute hochgeladen wurden, einzuschliessen, muss ich das betrachtete Zeitfenster bis zum 13.12. festlegen anstelle nur bis zum (standardmässig definierten) 12.12. Gibt es einen Grund dafür?

**Comment by grrd01** [comment]
Weil beim Datum der Zeitwert nicht mitgegeben wurde, wurden nur Bilder angezeigt, die <= 12.12.2017 00:00:00. Neu wird die Zeit auf 23:59;59 gesetzt.
fixed
