### ISSUE TITLE
Ort nach Ortsuche in Karte zentrieren

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#50]

**Comment by grrd01** [comment]
@RouStu : wo meinst du das: im Upload-Modal oder in der Hauptkarte?
Nur zentrieren oder auch zoomen?

**Comment by RouStu** [comment]
Mir ist es in der Hauptkarte aufgefallen. Zentrieren genügt mir.

**Comment by bweben** [comment]
Ist nun so, dass in der Hauptkarte nach Eingabe eines Ortes auf den entsprechenden "gepant" wird, das heisst der Marker wird möglichst in der Mitte zentriert aber mit Rücksicht auf die Aussengrenzen der Karte (der Schweiz)
