### ISSUE TITLE
inkorrekter Bildnachweis

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#52]
Der Bildnachweis ist zurzeit fehlerhaft:
Der Name darin stimmt nicht mit dem "Urheber" überein, sondern stammt von einer anderen Foto (s. Bild 1).
Zudem wird die Lizenz nicht immer richtig im Bildnachweis angezeigt (s. Bild 2). Dies tritt bei einem Bild auf, bei dem ich im Admin-Modus nachträglich die Lizenz geändert habe.

![image](https://user-images.githubusercontent.com/31846871/32494064-77ff9bde-c3c0-11e7-91ff-dad0a45bc6f3.png)

![image](https://user-images.githubusercontent.com/31846871/32494091-91a6d05c-c3c0-11e7-8149-b7b3e2126617.png)

**Comment by grrd01** [comment]
@RouStu : kann es sein, dass diese inkorrekten Zustände nur zustandekommen, wenn du über die "weiterblättern"Pfili auf ein nächstes Bild klickst? Dann werden u.U. die Angaben des vorigen Bildes angezeigt.
Wenn du hingegen über die Grund-Ansicht gehst, scheint alles zu stimmen?

**Comment by RouStu** [comment]
Genau so ist es.

**Comment by bweben** [comment]
Ist geflickt.
