### ISSUE TITLE
Sprachwechsel kaputt

### ISSUE THREAD

**Issue by grrd01** [grrd01/MobiLab#53]
Wenn ich auf dem Server (nachdem ich alle Tokens gelöscht habe) auf der deutschen Seite den FR-link anklicke, passiert nichts, und ich erhalte diese beiden Fehlermeldungen: 

POST http://138.68.87.41/api/client/lang 404 (Not Found)
...
vendor.f63219d6af44081a91aa.bundle.js:1 ERROR {
  "error": {
    "message": "",
    "stack": "",
    "name": "UnauthorizedError",
    "code": "credentials_required",
    "status": 404,
    "inner": {
      "message": ""
    }
  }
}

**Comment by bweben** [comment]
@grrd01 @RouStu im Moment ist auf dem Server gerade die Datenbank kaputt, da eine neue Version ausgerollt wird.

**Comment by RouStu** [comment]
Danke für den Hinweis!

**Comment by bweben** [comment]
Funktioniert wieder
