### ISSUE TITLE
Ortseingabe bei Upload

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#54]
Wenn beim Bildupload ein Ort eingegeben wird, wird dieser in der Regel gefunden und die Koordinaten werden entsprechend ausgefüllt. Wenn es sich dabei um den falschen Ort handelt, kann kein weiterer Ort direkt mit der Ortssuche gefunden werden, was ziemlich unpraktisch ist.

Beispiel:
- Eingabe: "Kien" -> es wird ein Punkt im Hinterland des Wallis gefunden
- 2. Eingabe: "Kien BE" -> der Punkt im Wallis verändert sich nicht -> das Uploadmodal muss dann meist geschlossen und wieder geöffnet werden, um einen neuen Ort eingeben zu können

Kann das Verhalten so angepasst werden, dass eine erneute Ortseingabe direkte Wirkung bezüglich Koordinaten und Pin hat?

**Comment by bweben** [comment]
Dieses Verhalten wurde bewusst so gemacht. Sobald das Feld nicht mehr leer ist, wird es befüllt und dementsprechend angepasst, ansonsten aber nicht.

**Comment by RouStu** [comment]
Mehrfache Ortseingabe mit Auswirkung auf Koordinaten ermöglichen, wenn die Koordinaten in der Zwischenzeit nicht manuell eingegeben wurden.
