### ISSUE TITLE
Optimierung der Bildrahmen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#55]
Die Rahmen werden zurzeit teilweise erst beim zweiten Hover richtig angezeigt. Bei Panoramabildern ist der Rahmen nie ganz richtig aufs Bildformat abgestimmt.

**Comment by grrd01** [comment]
Das Problem konnte gelöst werden, indem das Popup zweimal geöffnet wird:
```
      marker.openPopup();
      // debounce and reopen
      if (this.popupTimeout) {
        clearTimeout(this.popupTimeout);
      }
      this.popupTimeout = setTimeout(() => {
        marker.openPopup();
      }, 5);
```
Den Nobelpreis für Informatik gibts für diese Lösung wohl kaum...

**Comment by RouStu** [comment]
Der Rahmen um Panoramabilder wird bei mir noch nicht richtig angezeigt. Kann dies behoben werden?

![image](https://user-images.githubusercontent.com/31846871/33872282-83d31f0a-df16-11e7-83d9-75c0405a2522.png)

**Comment by grrd01** [comment]
fixed
