### ISSUE TITLE
Internet Explorer-Probleme

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#56]
- [x] Das Format gewisser Bilder der Bildserie auf der rechten Seite wird zum Teil falsch angezeigt.
- [x] Die Ortseingabe auf der Hauptseite funktioniert nicht.

**Comment by grrd01** [comment]
@bweben : CSS ist eine feine Sache..! ;-)
Offenbar lässt sich das Problem im IE durch das Entfernen der Zeile "display: inline-block" lösen:
```
.image-scroller > div {
    float: none;
    /*display: inline-block;*/
    padding: 0;
    min-width: 100%;
  }
```
Auf alle anderen Browser scheint dies keinen negativen Einfluss zu haben..
