### ISSUE TITLE
Adminmodus: Kein Umbruch in Kopfzeile

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#57]
Vorschlag: Weglassen des Wortes "Überschwemmungsbilder"

**Comment by grrd01** [comment]
Hm.. Das steht dort gar nicht..
@RouStu : meinst du "Kollektives Überschwemmungsgedächtnis"?

**Comment by RouStu** [comment]
@grrd01 : Bei mir siehts so aus:
![image](https://user-images.githubusercontent.com/31846871/32778661-084a5c86-c93b-11e7-9525-b1b2c1e26dc8.png)
Dort würde ich auf "Überschwemmungsbilder" verzichten. "Administrator" sollte in dieser Ansicht reichen.
Oder sprechen wir nicht vom selben?

**Comment by grrd01** [comment]
@RouStu : Im Moment sieht die Version auf dem Server anders aus als die neuste Version. Nathanael wird diesen Punkt mit dir anschauen.

**Comment by grrd01** [comment]
@RouStu , @bweben : Viel Platz könnte schon gewonnen werden, wenn man die langen Texte zum Blättern durch Glyphicons ersetzt: 
![image](https://user-images.githubusercontent.com/5230177/32783003-8e271bdc-c94a-11e7-821f-3eda48a17757.png)
Was meint ihr?

Noch mehr Platz gäbe es, wenn man auch das Logo durch ein Glyphicon ersetzen würde..

**Comment by grrd01** [comment]
@bweben : Im Georef-Modus sollte zudem der Button "Seite ändern" ausgeblendet werden. Er hat keine Funktion.

**Comment by RouStu** [comment]
- Die Texte "Erstes" etc. im Admin- und im Georef.-Modus durch Glyphicons zu ersetzen, gefällt mir sehr.
- Im Adminmodus sollte es dann zusammen mit Logo und "Administrator" genügend Platz geben, da die Nutzung ohnehin meist am Desktop-PC stattfindet.
- Der Georef.-Modus wird wohl auch mobil genutzt werden. Zurzeit fällt der Text "Verortung bestehender Bilder" ab einer gewissen Breite weg. Wäre es hier eine Möglichkeit, den Text ab einer gewissen Breite mit dem Pin zu ersetzen oder ist das nicht intuitiv? Dann wäre auf der ersten Zeile das Logo, der Pin und der Homebutton. Auf der zweiten Zeile wäre dann die Seitennavigation.
- Das Logo in ein Glyphicon umzuwandeln, sehe ich zurzeit nicht plastisch. Für Vorschläge bin ich aber immer offen.

**Comment by grrd01** [comment]
@RouStu : Möglich wäre beispielsweise, die Mobi-Seite des Logos mit dem allerseits bekannten und beliebten Paket-Sujet zu visualisieren:
![image](https://user-images.githubusercontent.com/5230177/32832734-d150eef8-c9fc-11e7-9164-7e6d558a3159.png)
et voilà: 80% Platzersparnis bei 100% Informationsgehalt:
![image](https://user-images.githubusercontent.com/5230177/32833034-c67751ce-c9fd-11e7-9f5e-83d38334823e.png)

sollte ein Witz sein, sorry..

**Comment by RouStu** [comment]
Hehe, nicht schlechter Vorschlag! Und das Glyphicon für den Titel wäre folgender (sorry, die offiziellen Glyphicons dazu hab ich noch nicht gefunden...):

![image](https://user-images.githubusercontent.com/31846871/32835541-c19cc630-ca06-11e7-81ba-644b2a527d2c.png)

**Comment by grrd01** [comment]
@RouStu : Hier noch eine weitere Idee:
![image](https://user-images.githubusercontent.com/5230177/32845604-693b857a-ca25-11e7-9bb1-8e6bb4f8671f.png)

**Comment by bweben** [comment]
Der Admin Modus hat nun nicht mehr 2 Add Admin Icons bei kleinen Geräten.

Ausserdem hier noch meine 50 Cent:
![logo](https://user-images.githubusercontent.com/10772590/32889278-8f14e214-caca-11e7-9bc5-172835b7420a.png)

**Comment by grrd01** [comment]
das lässt sich kombinieren:
![image](https://user-images.githubusercontent.com/5230177/32891397-b01107e2-cad2-11e7-903c-4b3f3dae44bd.png)
