### ISSUE TITLE
Gemeindename und -Nr. automatisch erfassen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#6]
Gemeindename und -Nr. (gemäss BfS) aus swissboundaries für jedes Bild erfassen

**Comment by bweben** [comment]
Ich bin der Meinung dies ist unnötig da dies aufgrund der Koordinaten des Bildes auch im Nachhinein ausgelesen werden kann. Aufgrund dessen denke ich macht es keinen Sinn die Nr. in der Datenbank zu erfassen.

**Comment by RouStu** [comment]
OK, wird zurzeit nicht weiterverfolgt.
