### ISSUE TITLE
Pinanzeige gerade hochgeladener Bilder

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#60]
Grüner Pin gerade hochgeladener Bilder nicht erst nach Refresh anzeigen.
Das Verhalten tritt zurzeit sporadisch auf.

**Comment by bweben** [comment]
Das könnte an einer langsamen Verarbeitung liegen, weiss es jedoch nicht genau.

**Comment by bweben** [comment]
Wenn ein Bild am hochladen ist, wird eine Ladeanimation angezeigt beim Upload-Icon. (Vielleicht mit Nummer von Anzahl hochzuladender Bildern).

**Comment by bweben** [comment]
Ist nun besser verständlich.
![image](https://user-images.githubusercontent.com/10772590/33475260-1a680c88-d67e-11e7-80a7-1d43a83936eb.png)

**Comment by RouStu** [comment]
Eine ähnliche Frage wie hier: #76 

Im Idealzustand werden in vielen Gebieten Clusters zu sehen sein. Sprich nach dem Upload verschwindet der grüne Pin in einem Cluster und man sieht nicht, wo die Foto lokalisiert ist und ob sie überhaupt hochgeladen wurde.
Wie seht Ihr die Möglichkeit, nach dem Bildupload (und nachdem die eingebaute Sanduhranimation beim Uploadknopf fertig gedreht hat) in der Hauptkarte auf den Bildstandort zu zoomen?

**Comment by RouStu** [comment]
Nach dem Upload soll der Standort als roter Pin im Vordergrund angezeigt werden, bis etwas anderes gehovert oder geklickt wird.

**Comment by bweben** [comment]
geändert
