### ISSUE TITLE
Uploadmodal: "Sanduhr" nach Bildauswahl

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#61]

**Comment by RouStu** [comment]
Gerade mir Gérard noch ein Designdetail besprochen: Vielleicht gäbe es die Möglichkeit, den Hintergrund der Sanduhr grau zu machen. Dafür müsste das gif transparent gemacht werden können...

**Comment by grrd01** [comment]
jetzt haben wir ein anderes gif mit transparentem hintergrund

**Comment by bweben** [comment]
Ladebild verkleiner.

**Comment by RouStu** [comment]
Kann es sein, dass eine alte Version der Sanduhr (zwei Kreise nebeneinander) z.T. immer noch vorkommen bei der Bildauswahl im Uploadmodal?

**Comment by bweben** [comment]
Ich denke dies liegt am Cache von Chrome, jedenfalls bei mir war es weg, nachdem ich die Seite mit `ctrl + r` neu geladen habe.
