### ISSUE TITLE
Internet Explorer - Adminmodus: falsche Bilder

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#63]
Es werden fälschlicherweise die bereits validierten Bilder angezeigt.

**Comment by bweben** [comment]
## Notizen
Wenn von Home in den Admin Modus gewechselt wird, tritt dieses Problem auf und wenn vom Admin Modus in den Home gewechselt wird, jedoch nicht wenn der Admin Modus offen ist und neu geladen wird.

**Comment by bweben** [comment]
Ist geflickt.
