### ISSUE TITLE
Uploadmodal: Datum wird nicht aus EXIF gelesen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#64]
Datum wird offenbar nicht aus EXIF gelesen, wenn das Bild um 00:00 aufgenommen wurde.

Bsp.:
![thun_brahmsquai 08 05](https://user-images.githubusercontent.com/31846871/32886032-b4e68890-cabf-11e7-9739-3ec1bf869326.jpg)

**Comment by bweben** [comment]
Wurde geflickt.

**Comment by RouStu** [comment]
Die erwähnte Foto oben wurde am 01.08.2005 00:00 aufgenommen. Wenn ich es nun hochlade, wird folgendes Datum automatisch herausgelesen: 14.11.2006. Woran könnte es liegen, dass ein m.E. zufällig generiertes Datum rauskommt?

**Comment by bweben** [comment]
Windows zeigt 01.08.2005 00:00 an, jedoch gibt es nur ein Datum im EXIF (wenn es mit dem Tool von uns gelesen wird) und das ist der 14.11.2006. Ich bin nicht sicher wieso / wie Windows auf dieses (2005) Datum kommt. Bei anderen Fotos mit Datum im EXIF stimmt es aber.

**Comment by RouStu** [comment]
Das Störende ist einzig, dass es sich beim Bild mit Sicherheit um ein Bild vom August 2005 handeln muss. Aber OK, wird demfall ein Sonderfall sein. Ich könnte mir etwa vorstellen, dass das Datum im EXIF mit einer unsauberen Methode im Nachhinein reingeschrieben wurde (die Uhrzeit "00:00" spricht u.a. dafür).

**Comment by bweben** [comment]
Dann ist es wirklich sehr speziell. Ich habe nun noch eine andere Art ausprobiert um die EXIF Daten auszulesen, aber auch dort kommt der 14.11.2006.
Deshalb denke ich wird es schwierig dieses Verhalten zu flicken.

**Comment by RouStu** [comment]
Kein Problem. Wenn wir keine Abweichungen bei "normalen", realistischen Daten feststellen, passt die Sache.
