### ISSUE TITLE
Adminmodus: Ergänzungen

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#66]
Möchte noch Folgendes in die Runde werfen: Wie sähe der Aufwand aus, den Adminmodus um weitere vier Elemente zu ergänzen (vor allem die ersten beiden Punkte):
- [x] das zweite Koordinatenpaar (Georef.-Backup)
- [x] Uploaddatum
- [x] Checkbox Publikation Mail-Adresse
- [x] Sprache des Users

Diese Ergänzungen hätten den Vorteil, dass die Bilddatenbank über längere Zeit mit dem Adminmodus eigenständig und zeitnah verwaltet werden könnte und potenziell wichtige Informationen nicht verborgen blieben.

**Comment by grrd01** [comment]
Das macht sicher Sinn

**Comment by RouStu** [comment]
Dieser Task ist zwar noch nicht "bereit zum Testen". Trotzdem bereits eine Rückmeldung: Mir ist aufgefallen, dass die Zeit des Uploads nicht immer korrekt angegeben wird:
![image](https://user-images.githubusercontent.com/31846871/33207521-4d198f0a-d10e-11e7-9339-e27f3ef8486b.png)

**Comment by bweben** [comment]
Meinnst du das Format?

**Comment by RouStu** [comment]
Ja, ich meinte die Zeit "11:9"

**Comment by bweben** [comment]
Auch bei Minuten! @me

**Comment by bweben** [comment]
Wirklich geflickt.

**Comment by RouStu** [comment]
Denke, es könnte nützlich sein, wenn die E-Mail-Adresse und die Checkbox für deren Publikation im Adminmodus angepasst werden können. Kann das geändert werden?

**Comment by bweben** [comment]
Ich denke dies wäre gegenüber des Uploaders falsch.
Nach meinem Verständnis lädt der Uploader die Bilder nach seinem besten Wissen und Gewissen hoch und füllt auch die Informationsfelder entsprechend aus. Ich denke es wäre falsch ihn hier zu "bevormunden" indem er die Daten vom Administrator wechseln könnte. Ausserdem könnte dies zu Unstimmigkeiten führen, falls jemals jemand entdecken würde dass die Email-Adresse sowie ob diese veröffentlicht werden darf oder nicht verändert wird.

Abschliessend kann noch gesagt werden, dass wenn ein Nutzer wirklich falsche / schlechte Eingaben gemacht hat kann das Bild gelöscht werden jedoch denke ich ist es nicht ratsam ein ändern der Email Adresse sowie dieses Häckchen zu zuzulassen.

**Comment by RouStu** [comment]
Vielleicht muss ich kurz darlegen, was meiner Überlegung zugrunde liegt: Es geht mir nicht darum, dass die E-Mail-Adresse und deren Publikation ohne das Wissen des Urhebers verändert werden kann. Mir geht es darum, Situationen zu vermeiden, die unangenehm sein könnten: Wenn zum Beispiel ein Urheber (z.B. ein Kanton) 50 Bilder inkl. umfangreicher Metadaten (z.B. detataillierte Beschreibungen) hochlädt und er nachträglich feststellt, dass die E-Mail-Adresse nicht korrekt eingetippt wurde oder der Publikationsstatus geändert werden muss, dann sollte meiner Meinung nach die Möglichkeit bestehen, diese Informationen in Absprache mit dem Urheber im Adminmodus zu ändern. Ebenfalls kann ich mir vorstellen, dass ein bestehendes Bildarchiv nach einiger Zeit ihre E-Mail-Adresse oder die Kontaktperson, auf die die E-Mail-Adresse lautete, ändert.

Bezüglich Publikationsstatus scheint mir wahrscheinlich, dass gewisse Leute nach dem Upload auf uns mit der Bitte zukommen, den Publikationsstatus zu ändern. Wenn wir dann sagen müssen, dass wir ihre Bilder löschen und sie diese nochmals mit dem korrigierten Publikationsstatus hochladen sollen, weicht dies von der guten Usability, die wir in diesem Projekt bisher verfolgt haben, ab.

Die Argumentation der Bevormundung des Benutzers macht für mich hier weniger Sinn, da wir sonst beispielsweise auch die von ihm definiterte Lizenz nicht ändern können dürften.

**Comment by bweben** [comment]
Ist geändert.

**Comment by RouStu** [comment]
Super, besten Dank!

**Comment by RouStu** [comment]
Wenn die Koordinaten im Adminmodus mit dem "Refresh"-Knopf auf die Ursprungskoordinaten zurückgestellt werden, wird die Position des Pins in der Karte nicht aktualisiert. Kann das geändert werden?

**Comment by bweben** [comment]
ist geflickt
