### ISSUE TITLE
Beschreibung Modal Detail zu Textarea ändern.

### ISSUE THREAD

**Issue by bweben** [grrd01/MobiLab#68]

**Comment by grrd01** [comment]
fixed

**Comment by bweben** [comment]
Zeilenumbruch erzwingen bei zu langen Texten ohne Zeilenumbruch.

**Comment by bweben** [comment]
Ist auch bei Emails ein Problem.
![image](https://user-images.githubusercontent.com/10772590/33361642-5330eeb4-d4d9-11e7-8d97-6341d871608e.png)

**Comment by grrd01** [comment]
fixed (auch bei Autor & Ort)
