### ISSUE TITLE
Georeferenzierung mit Ampelsystem

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#7]

**Comment by grrd01** [comment]
in Absprache mit Luzius: Allenfalls reduzierte, vollautomatische Version realisieren: Flag abspeichern:
- Georeferenz aus Exif (=grün)
- Georeferenz aus Klick auf Karte (=gelb)
- Georeferenz aus Eingabe Ortschaft (=rot)
So bleibten Gui und Prozess schlank

**Comment by bweben** [comment]
Wird nun gesetzt.
