### ISSUE TITLE
Lizenz CC BY-NC 4.0

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#71]
Könnt Ihr bitte noch folgende Lizenz einbauen? Sie betrifft Bilder aus bestehenden Bildarchiven. Sie soll im Adminmodus ausgewählt werden können - wie z.B. die Public Domain Mark. In den Lizenzbestimmungen kann sie an letzter Stelle auftauchen.

- Creative Commons-Lizenz
  CC BY-NC 4.0 
  [Link: https://creativecommons.org/licenses/by-nc/4.0/deed.de]: Die Bilder können unter Angabe des Bildnachweises für wissenschaftliche, private und nicht-kommerzielle Zwecke frei verwendet werden. Die Nutzung für kommerzielle Zwecke ist untersagt. Der Bildnachweis findet sich in der jeweiligen Bildlegende.

- Licence Creative Commons
  CC BY-NC 4.0
  [Link: https://creativecommons.org/licenses/by-nc/4.0/deed.fr]: Les images peuvent être librement utilisées à des fins scientifiques, privées et non commerciales. L'utilisation commerciale est interdite. Les crédits photographiques se trouvent dans la légende correspondante.

**Comment by bweben** [comment]
added.

**Comment by bweben** [comment]
not fixed, wrong license in modalDetail

**Comment by bweben** [comment]
fixed
