### ISSUE TITLE
geschützte Lizenz

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#72]
Gerade eine kleine Inkohärenz entdeckt: In der Detailansicht eines "geschützten" Bildes steht als Lizenz "geschützt". Werden dann die Lizenzbestimmungen geöffnet, findet sich dieser Begriff nicht wieder (analog im Französichen). Im Uploadmodal stellt sich das Problem nicht, im Hilfemodal aber schon.

Vorschlag:
- "alle Rechte vorbehalten" durch "geschützt" ersetzen
- "tous droits réservés" durch "protégé" ersetzen

Falls sich dadurch weitere Probleme ergeben sollten, bitte melden.

**Comment by grrd01** [comment]
fixed

**Comment by RouStu** [comment]
Noch eine Überlegung (hätte man auch schon fürher darauf kommen können, sry):
- Kann im Uploadmodal/Lizenzen/Hilfetext/geschützt der Beginn ("geschützt:") weggelassen werden?
Dann würde sich dieses Wort nicht wiederholen.
- Um die Übersicht zu gewährleisten, könnten wir zudem anschliessend die Reihenfolge ändern -> "geschützt, (c):". Die Auswirkung für das Hilfemodal/Lizenzbestimmungen scheint auch OK.

Analog fürs Französische.

**Comment by grrd01** [comment]
@RouStu : das geht leider nicht ohne weiteres. Der Hilfetext im Upload-Modal besteht für jeden Eintrag aus zwei Elementen: dem zur Auswahl stehenden Eintrag aus dem Dropdown und dem dazugehörigen Lizenztext aus dem HilfeModal:
![image](https://user-images.githubusercontent.com/5230177/33486244-94be6614-d6a9-11e7-8dbc-7003c18bd931.png)
Falls wir den rot markierten Teil unter "geschützt" entfernen, fehlt er danach auch unter "wiederverwendung erlaubt"

**Comment by RouStu** [comment]
Verstehe.
In dem Fall fällt mir gerade keine einfache Lösung ein, die die Ästhetik der Ansicht verbessern würde...

**Comment by grrd01** [comment]
@RouStu : falls du nach Verbesserungsmöglichkeiten betreffend der Ästhetik der Ansicht suchst, würde sich das Logo als quick win anbieten.
![image](https://user-images.githubusercontent.com/5230177/33488821-35acd7a6-d6b2-11e7-9c15-527c0a1dcd75.png)

**Comment by RouStu** [comment]
=)...in der Tat ästhetischer - obwohl das Paket wahrscheinlich seitlich wegrutschen könnte, wenn das Band nicht fest angezogen ist!
Ich hatte meine Aussage aber eigentlich nur auf die Ästhetik des Uploadmodal-Lizenz-Hilfetextes bezogen...

**Comment by grrd01** [comment]
@RouStu : Falls man hier noch was tun soll: bitte ergänzen. Ansonsten schliessen.
