### ISSUE TITLE
Bildlink

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#74]
Wenn ich einen Bildlink eingebe, z.B. http://138.68.87.41/fr/home/5a0429f59610a91fb65390ef/ , öffnet sich das richtige Bild. Der Bildlink darauf ist aber nicht mehr korrekt, die Bild-ID erscheint zweimal hintereinander: http://138.68.87.41/fr/home/5a0429f59610a91fb65390ef/5a0429f59610a91fb65390ef

Werden anschliessend weitere Bilder geöffnet, kommt die ID im Link unten auch jeweils zweimal vor.
Aufgefallen ist mir dieses Verhalten im französischen Modus.

**Comment by bweben** [comment]
fixed
