### ISSUE TITLE
Meldung bei Upload Problem

### ISSUE THREAD

**Issue by bweben** [grrd01/MobiLab#75]
## Beschreibung
Wenn ein Bild aus diversen Gründen nicht hochgeladen werden kann (beispielsweise weil der Client offline ist), kommt keine Meldung sondern es geht einfach nicht.
Dies wäre schöner mit einer Meldung.

**Comment by RouStu** [comment]
Diese Meldung erscheint bei mir und beim Bürokollegen mit Offline-Schalten im Chrome nicht. Funktioniert sie bei Dir?

**Comment by bweben** [comment]
![image](https://user-images.githubusercontent.com/10772590/34413388-7742d7ce-ebe3-11e7-883f-777d5d4d6c75.png)
Ja die erscheint bei mir, hast du eine gecachde Version? Und wann schaltest du Offline?

**Comment by RouStu** [comment]
Hmm. Habe den Cache gelöscht und mit Ctrl+Shift+r aktualisiert. Habe versucht offline zu schalten sowohl kurz vor dem Ausführen des Senden-Befehls als auch vor dem Öffnen des Uploadmodals.

**Comment by bweben** [comment]
Sehr komisch, das hat bei mir zu eben dieser Meldung geführt.

**Comment by RouStu** [comment]
OK, werde es mal noch von zu Hause aus versuchen.

**Comment by RouStu** [comment]
Also, mir gelingt es nicht, dass die Meldung angezeigt wird. Vielleicht müssen wir einmal kurz zusammen die Sache anschauen?

**Comment by RouStu** [comment]
Die deutsche Version wird bei mir nun korrekt angezeigt - danke!
