### ISSUE TITLE
Detailansicht: Ort des Bildes auf der Karte

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#76]
Wenn ein Bild in der Detailansicht geöffnet wird - z.B. nach dem Erhalt des entsprechenden Bildlinks -, gibt es, soweit ich weiss, keine Möglichkeit, sich den Bildort direkt auf der Karte anzuzeigen. Dies funktioniert nur, wenn das Bild per Zufall rechts bzw. unten in der Vorschau sichtbar ist.

Seht Ihr den Bedarf und eine einfache Möglichkeit, etwas Hilfreiches hierzu einzubauen (z.B. Link auf Karte mit entsprechendem Pin und Thumbnail)?

**Comment by bweben** [comment]
Ist nun so geändert, dass die Bilder rechts oder unten auf dieser Seite angezeigt werden, auf der auch das aktuell geöffnete Bild ist. Es wird zwar nicht zum Bild gescrollt jedoch sollte es nicht allzu schwierig sein bei 10 Bildern das Aktuelle zu finden.

**Comment by RouStu** [comment]
Funktioniert gut, danke.
Ich habe mir soeben noch die Frage gestellt, ob bei der Eingabe des Bildlinks in der Adresszeile die Karte im Hintergrund allenfalls gerade auf den Bildort zoomen könnte. Dann wäre nach dem Schliessen der Detailansicht gerade der Bildort ersichtlich.
Falls dies aber die Logik der sonstigen Darstellung durcheinander bringt - bitte wieder vergessen.

**Comment by RouStu** [comment]
Der Standort soll als roter Pin im Vordergrund angezeigt werden, bis etwas anderes gehovert oder geklickt wird.

**Comment by bweben** [comment]
added
