### ISSUE TITLE
Neues Tab Fotoscanner

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#77]
Neues Tab bitte gemäss Dateien (de/fr) einfügen.

[171214 Scannerapp.docx](https://github.com/grrd01/MobiLab/files/1606192/171214.Scannerapp.docx)
[171214 Scannerapp_fr.docx](https://github.com/grrd01/MobiLab/files/1606193/171214.Scannerapp_fr.docx)

**Comment by bweben** [comment]
fixed

**Comment by RouStu** [comment]
Danke!
Wäre es möglich, die erste Zeile in dt und fr (zurzeit fett: "Nur analoge Fotos zur Hand?" und "Numérisation des photos argentiques") als Tabtitel zu verwenden und sie im Tab selber entsprechend zu löschen? "Fotoscanner" und "Scanner photo" fällt dann im Tabtitel weg, was aber nicht tragisch ist. Erfreulicherweise würde dann ebenfalls der Fettdruck im Tab selber wegfallen, womit ein schöneres Bild entsteht.

**Comment by bweben** [comment]
Ist geändert.
![image](https://user-images.githubusercontent.com/10772590/34822240-7dc44d06-f6c6-11e7-8b29-c2e296388467.png)
