### ISSUE TITLE
erweitertes Uploadmodal: mehrere Karten

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#8]
Schneller Switch zwischen mehreren Karten, Luftbildern und Google-Streetview

**Comment by grrd01** [comment]
das eingesetzte Karten-Framework Leaflet/Mapbox unterstützt mehrere Kartendarstellungen (Satelit, Stassenkarte, ...) Ich baue momentan eine Demo mit mehreren Beispielen, danach können wir die gewünschten Ansichten bestimmen.
Diese können sowohl in der Grundkarte als auch im Uploadmodal integriert werden.

**Comment by RouStu** [comment]
Klingt sehr gut!
