### ISSUE TITLE
Bildlink: Sprachenproblematik

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#80]
Wenn das GUI auf Deutsch eingestellt ist und dann ein französicher Bildlink (z.B. http://138.68.87.41/fr/home/5a0189089fc44425cc16b905) geöffnet wird, wird bloss die deutsche Startseite angezeigt. Dies kann etwa beim Versand des Bildlinks an einen Kollegen in einer anderen Sprachregion ziemlich mühsam sein (ist mir eben mit dem Kanton Freiburg fast passiert).

Gäbe es die Möglichkeit, diesen Bildlink sprachunabhängig zu generieren?

**Comment by bweben** [comment]
Ist geflickt

**Comment by RouStu** [comment]
Funktioniert bei mir noch so wie vorher. Was wurde genau geändert?

**Comment by bweben** [comment]
War noch ein kleiner Fehler verbaut, funktioniert nun.
