### ISSUE TITLE
Lizenz CC BY-NC-ND 4.0

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#83]
Könnt Ihr bitte noch folgende Lizenz einbauen? Sie betrifft Bilder aus bestehenden Bildarchiven. Sie soll im Adminmodus ausgewählt werden können – analog zur Lizenz CC BY-NC. In den Lizenzbestimmungen kann sie an letzter Stelle auftauchen.

Creative Commons-Lizenz CC BY-NC-ND 4.0
[Link: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.de]: Die Bilder können unter Angabe des Bildnachweises für wissenschaftliche, private und nicht-kommerzielle Zwecke frei verwendet werden. Die Nutzung für kommerzielle Zwecke und die Bearbeitung der Bilder sind untersagt. Der Bildnachweis findet sich in der jeweiligen Bildlegende.

Licence Creative Commons CC BY-NC-ND 4.0
[Link: https://creativecommons.org/licenses/by-nc-nd/4.0/deed.fr]: Les images peuvent être librement utilisées à des fins scientifiques, privées et non commerciales. L'utilisation commerciale et la modification des images sont interdites. Les crédits photographiques se trouvent dans la légende correspondante.

**Comment by grrd01** [comment]
fixed, aber noch nicht publiziert.
