### ISSUE TITLE
erweitertes Uploadmodal: mehrere Fotos

### ISSUE THREAD

**Issue by RouStu** [grrd01/MobiLab#9]
Für verbesserte Georeferenzierung:
- Switch zwischen mehreren Fotos
- mehrere Fotos sollen für Vergleich sichtbar bleiben (analog geosetter.de)

**Comment by grrd01** [comment]
das Upload-Modal wird für den Upload mehrerer Bilder so optimiert, dass die Felder, welche vermutlich nicht ändern (Urheber, Mail, ..) nicht gelöscht werden, nachdem ein erstes Foto hochgeladen wurde. Somit gehts beim zweiten schneller.
